# Generated by Django 4.0.3 on 2023-06-02 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=26, verbose_name='Name')),
                ('surname', models.CharField(max_length=26, verbose_name='Surname')),
                ('reset_password_token', models.UUIDField(blank=True, default=None, null=True, verbose_name='Reset password token')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True, verbose_name='City')),
                ('date_of_birth', models.DateField(blank=True, max_length=15, null=True, verbose_name='Date of birth')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Company name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number')),
                ('role', models.CharField(choices=[('Предприниматель', 'Предприниматель'), ('Поставщик', 'Поставщик')], max_length=200, verbose_name='Role')),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=main.models.user_profile_directory_path, verbose_name='Profile image')),
            ],
        ),
        migrations.CreateModel(
            name='RespondState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принят', 'Принят'), ('Отказ', 'Отказ')], max_length=200, verbose_name='State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Respondent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company_name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=main.models.user_image_directory_path, verbose_name='Ad image')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='Edit date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('responders', models.ManyToManyField(to='main.respond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Profile'),
        ),
        migrations.CreateModel(
            name='FavoriteAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ad')},
            },
        ),
    ]
