# Generated by Django 4.0.3 on 2023-06-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_respond_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respond',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
