# Generated by Django 4.1.7 on 2023-04-11 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ad_responders_alter_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Edit date'),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
