# Generated by Django 4.1.7 on 2023-04-15 14:19

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ad_create_date_ad_edit_date_ad_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_image_directory_path, verbose_name='Ad image'),
        ),
    ]
