# Generated by Django 4.0.3 on 2023-05-11 14:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ad_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_profile_directory_path, verbose_name='Profile image'),
        ),
    ]
