# Generated by Django 4.0.3 on 2023-05-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_favoritead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritead',
            unique_together={('user', 'ad')},
        ),
    ]
